#!/usr/bin/env bash
set -o errexit


help_doc (){
	cat <<-'HelpDoc'
		exec-in-term: execute a command in a new interactive terminal window

		-t|--terminal      # Optional, filename of terminal to use
		-d|--working-dir   # Optional, directory to open in
		-p|--persist       # Optional, leave the terminal open after execution, makes -x optional
		-x|--execute       # String to be executed
		--stdin            # Read string to be executed from stdin
		-h|--help          # Output help

		Examples of use:
		  exec-in-term -p -x 'echo hello'
		  exec-in-term -x 'echo hello'
		  exec-in-term --stdin <<< 'echo hello'

	HelpDoc
	exit 0
}



print_stderr() {
	if [[ $1 == '0' ]]; then
		[[ $2 ]] && printf "$2" "${@:3}" 1>&2 || :
	else
		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2 || :
		exit "$1"
	fi
}



# Check dependencies
type setsid nohup 1>/dev/null



[[ $1 ]] || help_doc
while [[ $1 ]]; do
	case $1 in
		'--terminal'|'-t')
			shift; terminal=$1 ;;
		'--working-dir'|'-d')
			shift; cd -- "$1" ;;
		'--persist'|'-p')
			persist=1 ;;
		'--execute'|'-x')
			shift; execute_cmd=$1 ;;
		'--stdin')
			execute_cmd=$(</dev/stdin) ;;
		'--help'|'-h')
			help_doc ;;
		*)
			print_stderr 1 '%s\n' 'unrecognized parameter: '"$1" ;;
	esac
	shift
done



# Define the terminal execute command
declare -A terminal_to_command=(
	['alacritty']='alacritty -e'
	['xfce4-terminal']='xfce4-terminal -x'
)

declare -A terminal_aliases=(
	['default']='alacritty'
	['xfce']='xfce4-terminal'
)

terminal_try_arr=(
	alacritty
	xfce4-terminal
)



# Fallback through terminals to use
if [[ ! $terminal ]]; then
	for terminal_try in ${terminal_try_arr[@]}; do
		if type "$terminal_try" &> /dev/null; then
			terminal=$terminal_try
			break
		fi
	done

else
	terminal=${terminal_aliases[$terminal]}
fi



# Check terminal exists
[[ $terminal ]] || print_stderr 1 '%s\n' 'no supported terminal installed'
type -- "$terminal" 1>/dev/null



# If there's no command to execute, just open the terminal
if [[ ! $execute_cmd ]]; then
	setsid -f nohup $terminal &> /dev/null & disown
	exit 0
fi



# Define terminal command
terminal_cmd=${terminal_to_command["$terminal"]}
[[ $terminal_cmd ]] || print_stderr 1 '%s\n' 'unsupported terminal'



# Open the terminal
if [[ $persist ]]; then
	# Create a named pipe with 0600 permissions (rw for user only).
	fifo_path='/tmp/open_in_terminal__'$$'_'$RANDOM$RANDOM
	[[ -e $fifo_path ]] && rm "$fifo_path"
	mkfifo --mode 0600 "$fifo_path"

	# Create the .bashrc remix
	printf -v bashrc_remix '%s\n%s\n' "$(< $HOME/.bashrc)" "$execute_cmd"

	# Open terminal and have bash listen on the named pipe for the rcfile
	setsid -f nohup $terminal_cmd bash --rcfile "$fifo_path" &> /dev/null & disown

	# Deliver the remixed .bashrc over the named pipe
	printf '%s' "$bashrc_remix" > "$fifo_path"

	# Delete the named pipe
	rm "$fifo_path"

else
	[[ $execute_cmd ]] || print_stderr 1 '%s\n' 'nothing to execute'
	setsid -f nohup $terminal_cmd bash -i -c "$execute_cmd" &> /dev/null & disown

fi




